### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by Cains1978** [Und3rf10w/Aggressor-scripts#3]
When I attempt to load this script into Cobalt Strike via the Script Manager I receive the following error "Could not load...... Error: Syntax error at line 29 beacon_command-register"

**Comment by Und3rf10w** [comment]
Hello,

Which script specifically are you trying to load?

**Comment by Und3rf10w** [comment]
Actually, looks like it was `uploadbackdoor.cna`

I had a small syntax error in it, pushed a commit that should have fixed it. If not, please reopen this issue.

**Comment by Cains1978** [comment]
The scipt that I was referring to was actually the uploadbackdoor-menu.cna
but I will update my uploadbackdoor.cna as well

Thanks

**Comment by Cains1978** [comment]
Sorry for the confusion, you were right that the uploadbackdoor.cna had the
syntax issue but the uploadbackdoor-menu.cna also has an issue with what
appears to be a missing perenthise on line 20 I believe but will have to
check

**Comment by Und3rf10w** [comment]
Yeah, that one had a similar issue. Pushed a fix, should be good, but I haven't had the chance to test it.
