### ISSUE TITLE
ntfsADSBackdoor.cna will not load

### ISSUE THREAD

**Issue by Cains1978** [Und3rf10w/Aggressor-scripts#6]
When I attempt to load this into Cobalt Strike via the Scripting Manager I receive the following error "unknown expression at line 21 : txt and unknown expression at line 21: adfjklbalgjbr"

**Comment by Und3rf10w** [comment]
Okay, pushed commit b885050, this at least lets the script load.

There's a bug in this script that doesn't change to the correct location in the folder. As an alternative, please see [oldb00t's script](https://github.com/oldb00t/Aggressor-scripts/blob/master/ExampleADS/example-ads.cna).
